server:
  port: 8081
logging:
#  file: /var/log/galaxy/web.log
  level.*: INFO
  level.site.blmdz: DEBUG
session:
  source: redis
  redis-prefix: blmdz
  redis-cluster: false
  redis-test-on-borrow: true
  redis-max-idle: 0
  redis-max-total: 5
  redis-index: 0
  redis-host: 127.0.0.1
  redis-port: 6379
  redis-sentinel-master-name: 
  redis-sentinel-hosts: 
  redis-auth: 
  cookie-name: lm
  cookie-domain: 127.0.0.1
  cookie-max-age: 10
  cookie-context-path: /
  max-inactive-interval: 10
#session:
#  cookie-domain: www.nbportshop.com
#  cookie-context-path: /
#  cookie-name: msid
#  cookie-max-age: 1800
#  source: redis
#  serialize-type: json
#  redis-host: 127.0.0.1
#  redis-port: 6379
#  redis-index: 1
#  redis-cluster: false
#  redis-test-on-borrow: true
#  redis-max-total: 10
#  redis-max-idle: 0
#  redis-prefix: afsession
#  max-inactive-interval: 1800