### 组件资源
components:
  c:
    category: ADMIN
    name: 小C
    desc: 小C的渲染
    uri: cn.blmdz.hbs.services.Tests:testa
  b:
    category: ADMIN
    name: 小B
    desc: 小B的渲染
    uri: cn.blmdz.hbs.services.Tests:bbb
    
### 默认权限
defaults:
  GLOBAL:
    requests:
      - get: /login
    resources:
      - xxx
  LOGIN:
    requests:
  ADMIN:
    requests:
  XXX:
    requests:
    
### 权限树
trees:
  XXX:
    abc:
      name:
      resources:
      children:
        bcd:
        name:
        resources:
        
### 资源列表
resources:
  abc:
    requests:
      - get:
      - post:
      