server:
  context-path: /
  port: 8081
  
qxx:
  root: classpath:/
  home: apps
  locale: zh_CN
  devMode: true
  
  oos:
    endpoint: http://oss-cn-shanghai.aliyuncs.com
    accessKey: xxx
    accessSecret: xxx
    bucketName: xxx
    
logging:
  file: /home/xpoll/log/hbs-web.log
  level.*: INFO
  level.cn.blmdz: DEBUG
    
session:
  cookie-domain: 127.0.0.1
  cookie-context-path: /
  cookie-name: qxx
  cookie-max-age: 1800
  source: redis
  serialize-type: json
  redis-index: 0
  redis-prefix: qxxsession
    
redis:
  host: 127.0.0.1
  port: 6379
  
# spring 安全监控
management:
  security:
    enabled: false