logging:
  file: /home/xpoll/log/xpoll-web.log
  level.*: INFO
  level.cn.blmdz: DEBUG
server:
  context-path: /
  port: 8082
  session:
    timeout: 1800

pampas:
  rootPath: /home/xpoll
  apps:
    - key: PC
      assetsHome: feebas
  mvc:
    ignoreInterceptors:
      - Login
      - Auth
    customInterceptors:
      #- loginInterceptor
      #- authInterceptor
  redis:
    host: 127.0.0.1
    port: 6379
  design:
    enable: true
  locale: zh_CN
  devMode: true